fghch

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -19,11 +19,15 @@ jobs:
           wget https://download.oracle.com/otn_software/linux/instantclient/214000/instantclient-sqlplus-linux.x64-21.4.0.0.0dbru.zip
           sudo unzip instantclient-basic-linux.x64-21.4.0.0.0dbru.zip -d /opt/oracle
           sudo unzip instantclient-sqlplus-linux.x64-21.4.0.0.0dbru.zip -d /opt/oracle
-          sudo mkdir -p /opt/oracle
-          sudo mv instantclient_21_4 /opt/oracle
           echo 'export LD_LIBRARY_PATH=/opt/oracle/instantclient_21_4:$LD_LIBRARY_PATH' >> ~/.bashrc
           echo 'export PATH=$LD_LIBRARY_PATH:$PATH' >> ~/.bashrc
           source ~/.bashrc
+          if [ -d "/opt/oracle/instantclient_21_4" ]; then
+            mv /opt/oracle/instantclient_21_4 $HOME/instantclient_21_4
+          else
+            echo "Error: Directory '/opt/oracle/instantclient_21_4' not found."
+            exit 1
+          fi
           ./sqlplus -V
 
       - name: Set Environment and Run Script
